// examples/solid-basic/src/components/Sidebar.tsx
import { For, createEffect, createSignal, onCleanup } from 'solid-js';
import { useEditor } from './EditorProvider';
import { Doc, DocCollection } from '@blocksuite/store';

function getDocs(collection: DocCollection) {
  return [...collection.docs.values()].map(d => ({
    title: d.meta?.title || 'Untitled',
    id: d.id,
  }));
}

export function Sidebar() {
  const { editor, collection } = useEditor()!;

  const [docs, setDocs] = createSignal(getDocs(collection));
  const updateDocs = () => setDocs(getDocs(collection));

  createEffect(() => {
    const disposables = [
      collection.slots.docUpdated.on(updateDocs),
      editor.slots.docLinkClicked.on(updateDocs),
    ];
    onCleanup(() => disposables.forEach(d => d.dispose()));
  });

  return (
    <div class="sidebar">
      <div class="header">所有文档</div>
      <div class="doc-list">
        <For each={docs()}>
          {doc => (
            <div
              classList={{
                'doc-item': true,
                active: editor?.doc.id === doc.id,
              }}
              onClick={() => {
                editor.doc = collection.getDoc(doc.id) as Doc;
                updateDocs();
              }}
            >
              {doc.title}
            </div>
          )}
        </For>
      </div>
    </div>
  );
}

// examples/react-basic/src/components/Sidebar.tsx
import { useEffect, useState } from 'react';
import { Doc } from '@blocksuite/store';
import { useEditor } from '../editor/context';

const Sidebar = () => {
  const { collection, editor } = useEditor()!;
  const [docs, setDocs] = useState<Doc[]>([]);

  useEffect(() => {
    if (!collection || !editor) return;
    const updateDocs = () => {
      setDocs([...collection.docs.values()]);
    };
    updateDocs();

    const disposable = [
      collection.slots.docUpdated.on(updateDocs),
      editor.slots.docLinkClicked.on(updateDocs),
    ];

    return () => disposable.forEach(d => d.dispose());
  }, [collection, editor]);

  return (
    <div className="sidebar">
      <div className="header">所有文档</div>
      <div className="doc-list">
        {docs.map(doc => (
          <div
            className={`doc-item ${editor?.doc === doc ? 'active' : ''}`}
            key={doc.id}
            onClick={() => {
              if (editor) editor.doc = doc;
              setDocs([...collection!.docs.values()]);
            }}
          >
            {doc.meta?.title || 'Untitled'}
          </div>
        ))}
      </div>
    </div>
  );
};

export default Sidebar;
